// FitTrack Activity V2: Walk / Run / Cycle GPS with current + average metrics and better filtering.
(function(){
 const supabase=window.fitTrackSupabase,state=window.fitTrackState,app=document.getElementById('app'),toast=window.fitTrackShowToast;if(!supabase||!state||!app)return;
 let activity=null,watchId=null,tickTimer=null,observerBusy=false;
 const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
 const fmtTime=sec=>{sec=Math.max(0,Math.round(sec||0));const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=String(sec%60).padStart(2,'0');return h?`${h}:${String(m).padStart(2,'0')}:${s}`:`${m}:${s}`};
 function hav(a,b){const R=6371,dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lon-a.lon)*Math.PI/180,lat1=a.lat*Math.PI/180,lat2=b.lat*Math.PI/180,x=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
 async function user(){const{data}=await supabase.auth.getUser();return data?.user||null}
 function steps(km,h,type){if(type==='cycle'||!km)return 0;h=Math.max(120,Math.min(220,Number(h||170)));return Math.round(km*100000/(h*(type==='run'?.65:.415)))}
 function durationSec(){if(!activity)return 0;return Math.max(0,Math.round((activity.elapsedMs+(activity.status==='active'?Date.now()-activity.segmentStartedAt:0))/1000))}
 function currentSpeed(){if(!activity||activity.points.length<2)return 0;const pts=activity.points.slice(-4),first=pts[0],last=pts.at(-1),sec=Math.max(1,(last.ts-first.ts)/1000),km=hav(first,last);return Math.min(80,km/(sec/3600))}
 function metrics(){const seconds=durationSec(),distance=activity?.distanceKm||0,hours=seconds/3600,speed=hours?distance/hours:0,pace=distance?(seconds/60)/distance:0,nowSpeed=currentSpeed(),nowPace=nowSpeed>0?60/nowSpeed:0,met=activity?.type==='walk'?3.8:activity?.type==='run'?8.3:7.5,kg=activity?.weightKg||70,calories=Math.round(met*3.5*kg/200*(seconds/60));return{seconds,distance,speed,pace,nowSpeed,nowPace,calories:Math.max(0,calories),steps:steps(distance,activity?.heightCm,activity?.type)}}
 function paceText(p){if(!p||!Number.isFinite(p))return'--';const m=Math.floor(p),s=String(Math.round((p-m)*60)).padStart(2,'0');return`${m}:${s}`}
 function gpsLabel(){if(!activity?.gpsReady)return'Waiting for GPS';const a=activity.lastAccuracy||999;return a<=10?'Excellent GPS':a<=25?'Good GPS':a<=50?'Fair GPS':'Weak GPS'}
 function chooser(){app.innerHTML=`<div class="page-head"><div class="eyebrow">Outdoor activity</div><h1 class="page-title">Start activity</h1><p class="page-copy">Track distance, duration, pace or speed, calories and route using GPS.</p></div><section class="grid grid-3">${[['walk','Walk','pace · steps'],['run','Run','pace · steps'],['cycle','Cycle','speed · distance']].map(x=>`<article class="card activity-v2-choice"><div class="activity-v2-icon">${x[1][0]}</div><div class="card-title">${x[1]}</div><div class="card-subtitle">GPS distance · ${x[2]} · calories</div><button class="primary-btn full-btn" data-activity-start="${x[0]}">Start ${x[1]}</button></article>`).join('')}</section><section class="card" style="margin-top:14px"><div class="section-title">For best accuracy</div><p class="page-copy">Use outdoors, enable Precise Location, and wait a few seconds for a good GPS signal before moving.</p></section>`}
 function renderLive(){if(!activity||state.route!=='ride')return;const m=metrics(),cycle=activity.type==='cycle';app.innerHTML=`<div class="page-head"><div class="eyebrow">${esc(activity.type.toUpperCase())}</div><h1 class="page-title">${activity.status==='paused'?'Paused':'Activity in progress'}</h1><p class="page-copy">${gpsLabel()}${activity.lastAccuracy?` · ±${Math.round(activity.lastAccuracy)} m`:''}</p></div><section class="activity-v2-hero"><div><span>Distance</span><strong>${m.distance.toFixed(2)} km</strong></div><div><span>Duration</span><strong>${fmtTime(m.seconds)}</strong></div></section><section class="grid grid-2" style="margin-top:14px"><article class="card"><div class="eyebrow">Current ${cycle?'speed':'pace'}</div><div class="metric metric-sm">${cycle?m.nowSpeed.toFixed(1):paceText(m.nowPace)}</div><div class="metric-label">${cycle?'km/h':'min/km'}</div></article><article class="card"><div class="eyebrow">Average ${cycle?'speed':'pace'}</div><div class="metric metric-sm">${cycle?m.speed.toFixed(1):paceText(m.pace)}</div><div class="metric-label">${cycle?'km/h':'min/km'}</div></article><article class="card"><div class="eyebrow">Calories</div><div class="metric metric-sm">${m.calories}</div><div class="metric-label">estimated kcal</div></article>${!cycle?`<article class="card"><div class="eyebrow">Steps</div><div class="metric metric-sm">${m.steps.toLocaleString()}</div><div class="metric-label">estimated</div></article>`:`<article class="card"><div class="eyebrow">GPS points</div><div class="metric metric-sm">${activity.points.length}</div><div class="metric-label">route samples</div></article>`}</section><section class="card" style="margin-top:14px"><div class="map-panel"><div class="map-grid"></div><div class="map-label">Route recording · ${gpsLabel()}</div></div></section><div class="grid grid-2" style="margin-top:14px"><button class="secondary-btn" data-activity-pause>${activity.status==='paused'?'Resume':'Pause'}</button><button class="primary-btn" data-activity-finish>Finish</button></div>`}
 function onPosition(pos){if(!activity||activity.status!=='active')return;const c=pos.coords;activity.lastAccuracy=c.accuracy||null;if(c.accuracy&&c.accuracy>60){renderLive();return}const p={lat:c.latitude,lon:c.longitude,ts:pos.timestamp,accuracy:c.accuracy};const prev=activity.points.at(-1);if(prev){const d=hav(prev,p),dt=Math.max(1,(p.ts-prev.ts)/1000),instant=d/(dt/3600);if(d>0.003&&d<0.2&&instant<65)activity.distanceKm+=d}activity.points.push(p);activity.gpsReady=true;renderLive()}
 function onError(err){console.warn('FitTrack GPS:',err?.message);toast?.('GPS unavailable. Check location permission.')}
 async function begin(type){if(!navigator.geolocation)return toast?.('GPS is not supported on this device');const u=await user();if(!u)return toast?.('Sign in to track an activity');let weightKg=70,heightCm=170;const{data:p}=await supabase.from('profiles').select('weight_kg,height_cm').eq('id',u.id).maybeSingle();if(p?.weight_kg)weightKg=Number(p.weight_kg);if(p?.height_cm)heightCm=Number(p.height_cm);activity={type,userId:u.id,status:'active',startedAt:new Date().toISOString(),segmentStartedAt:Date.now(),elapsedMs:0,distanceKm:0,points:[],gpsReady:false,lastAccuracy:null,weightKg,heightCm};watchId=navigator.geolocation.watchPosition(onPosition,onError,{enableHighAccuracy:true,maximumAge:500,timeout:15000});tickTimer=setInterval(()=>activity?.status==='active'&&renderLive(),1000);renderLive()}
 window.fitTrackStartActivity=type=>{state.route='ride';document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route==='ride'));window.fitTrackRender?.();setTimeout(()=>begin(type),0)};
 function pause(){if(!activity)return;if(activity.status==='active'){activity.elapsedMs+=Date.now()-activity.segmentStartedAt;activity.status='paused'}else{activity.status='active';activity.segmentStartedAt=Date.now()}renderLive()}
 function stopGps(){if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=null;if(tickTimer)clearInterval(tickTimer);tickTimer=null}
 async function finish(){if(!activity)return;if(activity.status==='active')activity.elapsedMs+=Date.now()-activity.segmentStartedAt;activity.status='finished';stopGps();const m=metrics(),route={type:'LineString',coordinates:activity.points.map(p=>[p.lon,p.lat]),properties:{accuracy_m:activity.points.map(p=>p.accuracy??null)}};const{error}=await supabase.from('activity_sessions').insert({user_id:activity.userId,activity_type:activity.type,started_at:activity.startedAt,ended_at:new Date().toISOString(),duration_seconds:m.seconds,distance_km:Number(m.distance.toFixed(3)),avg_speed_kmh:Number(m.speed.toFixed(2)),avg_pace_min_per_km:m.distance?Number(m.pace.toFixed(2)):null,estimated_calories:m.calories,estimated_steps:activity.type==='cycle'?null:m.steps,route_geojson:route});if(error){toast?.('Could not save activity');activity.status='paused';return renderLive()}const type=activity.type;app.innerHTML=`<div class="page-head"><div class="eyebrow">Activity saved</div><h1 class="page-title">${type[0].toUpperCase()+type.slice(1)} complete</h1></div><section class="grid grid-2"><article class="card"><div class="metric">${m.distance.toFixed(2)}</div><div class="metric-label">km</div></article><article class="card"><div class="metric">${fmtTime(m.seconds)}</div><div class="metric-label">duration</div></article><article class="card"><div class="metric">${type==='cycle'?m.speed.toFixed(1):paceText(m.pace)}</div><div class="metric-label">${type==='cycle'?'avg km/h':'avg min/km'}</div></article><article class="card"><div class="metric">${m.calories}</div><div class="metric-label">estimated kcal</div></article></section><button class="primary-btn full-btn" data-activity-done>Done</button>`;activity=null}
 function maybe(){if(state.route!=='ride')return;activity?renderLive():chooser()}
 document.addEventListener('click',e=>{const s=e.target.closest('[data-activity-start]');if(s)return begin(s.dataset.activityStart);if(e.target.closest('[data-activity-pause]'))return pause();if(e.target.closest('[data-activity-finish]'))return finish();if(e.target.closest('[data-activity-done]'))return chooser();if(e.target.closest('[data-route="ride"]'))setTimeout(maybe,0)});
 new MutationObserver(()=>{if(observerBusy)return;observerBusy=true;setTimeout(()=>{observerBusy=false;if(state.route==='ride'&&!app.querySelector('[data-activity-start]')&&!app.querySelector('[data-activity-pause]')&&!app.querySelector('[data-activity-done]'))maybe()},40)}).observe(app,{childList:true});
})();