// FitTrack Activity V4: foreground-safe GPS tracking with wake lock, active polling and stable pace.
(function(){
 const supabase=window.fitTrackSupabase,state=window.fitTrackState,app=document.getElementById('app'),toast=window.fitTrackShowToast;if(!supabase||!state||!app)return;
 let activity=null,watchId=null,tickTimer=null,gpsPulseTimer=null,wakeLock=null,pulseBusy=false,observerBusy=false;
 const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
 const fmtTime=sec=>{sec=Math.max(0,Math.round(sec||0));const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=String(sec%60).padStart(2,'0');return h?`${h}:${String(m).padStart(2,'0')}:${s}`:`${m}:${s}`};
 function hav(a,b){const R=6371,dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lon-a.lon)*Math.PI/180,lat1=a.lat*Math.PI/180,lat2=b.lat*Math.PI/180,x=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
 async function user(){const{data}=await supabase.auth.getUser();return data?.user||null}
 function limits(type){return type==='cycle'?{accuracy:80,maxSpeed:70,minMove:1.5,maxMove:8}:type==='run'?{accuracy:60,maxSpeed:30,minMove:.8,maxMove:6}:{accuracy:60,maxSpeed:14,minMove:.7,maxMove:5}}
 function steps(km,h,type){if(type==='cycle'||!km)return 0;h=Math.max(120,Math.min(220,Number(h||170)));const strideRatio=type==='run'?.65:.415,strideM=(h/100)*strideRatio;return Math.round(km*1000/strideM)}
 function durationSec(){if(!activity)return 0;return Math.max(0,Math.round((activity.elapsedMs+(activity.status==='active'?Date.now()-activity.segmentStartedAt:0))/1000))}
 function currentSpeed(){if(!activity)return 0;let v=Number(activity.currentSpeedKmh||0);if(activity.lastMovementAt&&Date.now()-activity.lastMovementAt>9000)v=0;return Math.max(0,v)}
 function metrics(){const seconds=durationSec(),distance=activity?.distanceKm||0,hours=seconds/3600,speed=hours?distance/hours:0,pace=distance?(seconds/60)/distance:0,nowSpeed=currentSpeed(),nowPace=nowSpeed>=.8?60/nowSpeed:0,met=activity?.type==='walk'?3.8:activity?.type==='run'?8.3:7.5,kg=activity?.weightKg||70,calories=Math.round(met*3.5*kg/200*(seconds/60));return{seconds,distance,speed,pace,nowSpeed,nowPace,calories:Math.max(0,calories),steps:steps(distance,activity?.heightCm,activity?.type)}}
 function paceText(p){if(!p||!Number.isFinite(p))return'--';const total=Math.max(0,Math.round(p*60)),m=Math.floor(total/60),s=String(total%60).padStart(2,'0');return`${m}:${s}`}
 function sampleAge(){return activity?.lastGpsAt?Math.max(0,(Date.now()-activity.lastGpsAt)/1000):Infinity}
 function gpsLabel(){if(!activity?.gpsReady)return'Waiting for accurate GPS';const age=sampleAge();if(age>15)return'GPS updates paused';if(age>8)return'GPS updates slow';const a=activity.lastAccuracy||999;return a<=10?'Excellent GPS':a<=20?'Good GPS':a<=40?'Fair GPS':'Weak GPS'}
 async function requestWakeLock(){if(!activity||activity.status!=='active'||document.visibilityState!=='visible'||!('wakeLock'in navigator))return;try{if(!wakeLock||wakeLock.released){wakeLock=await navigator.wakeLock.request('screen');wakeLock.addEventListener?.('release',()=>{wakeLock=null})}}catch(e){wakeLock=null;console.warn('FitTrack wake lock unavailable',e)}}
 async function releaseWakeLock(){try{await wakeLock?.release?.()}catch{}wakeLock=null}
 function chooser(){app.innerHTML=`<div class="page-head"><div class="eyebrow">Outdoor activity</div><h1 class="page-title">Start activity</h1><p class="page-copy">Track distance, duration, pace or speed, calories and route using GPS.</p></div><section class="grid grid-3">${[['walk','Walk','pace · steps'],['run','Run','pace · steps'],['cycle','Cycle','speed · distance']].map(x=>`<article class="card activity-v2-choice"><div class="activity-v2-icon">${x[1][0]}</div><div class="card-title">${x[1]}</div><div class="card-subtitle">GPS distance · ${x[2]} · calories</div><button class="primary-btn full-btn" data-activity-start="${x[0]}">Start ${x[1]}</button></article>`).join('')}</section><section class="card" style="margin-top:14px"><div class="section-title">For best accuracy</div><p class="page-copy">FitTrack keeps the screen awake during tracking where supported. Keep the app in the foreground and enable Precise Location for accurate distance.</p></section>`}
 function renderLive(){if(!activity||state.route!=='ride')return;const m=metrics(),cycle=activity.type==='cycle',age=sampleAge(),quality=activity.pausedByVisibility?'Tracking paused when FitTrack left the foreground':`${gpsLabel()}${activity.lastAccuracy?` · ±${Math.round(activity.lastAccuracy)} m`:''}${Number.isFinite(age)?` · ${Math.round(age)}s ago`:''}`;app.innerHTML=`<div class="page-head"><div class="eyebrow">${esc(activity.type.toUpperCase())}</div><h1 class="page-title">${activity.status==='paused'?'Paused':'Activity in progress'}</h1><p class="page-copy">${quality}</p></div><section class="activity-v2-hero"><div><span>Distance</span><strong>${m.distance.toFixed(2)} km</strong></div><div><span>Duration</span><strong>${fmtTime(m.seconds)}</strong></div></section><section class="grid grid-2" style="margin-top:14px"><article class="card"><div class="eyebrow">Current ${cycle?'speed':'pace'}</div><div class="metric metric-sm">${cycle?m.nowSpeed.toFixed(1):paceText(m.nowPace)}</div><div class="metric-label">${cycle?'km/h':'min/km'}</div></article><article class="card"><div class="eyebrow">Average ${cycle?'speed':'pace'}</div><div class="metric metric-sm">${cycle?m.speed.toFixed(1):paceText(m.pace)}</div><div class="metric-label">${cycle?'km/h':'min/km'}</div></article><article class="card"><div class="eyebrow">Calories</div><div class="metric metric-sm">${m.calories}</div><div class="metric-label">estimated kcal</div></article>${!cycle?`<article class="card"><div class="eyebrow">Steps</div><div class="metric metric-sm">${m.steps.toLocaleString()}</div><div class="metric-label">GPS-estimated</div></article>`:`<article class="card"><div class="eyebrow">GPS samples</div><div class="metric metric-sm">${activity.points.length}</div><div class="metric-label">accepted samples</div></article>`}</section><section class="card" style="margin-top:14px"><div class="map-panel"><div class="map-grid"></div><div class="map-label">${gpsLabel()} · ${activity.points.length} samples</div></div></section>${activity.pausedByVisibility?`<section class="card" style="margin-top:14px;border-color:rgba(255,106,0,.35)"><div class="section-title">Tracking protection</div><p class="page-copy">The activity was paused because the app became hidden. This prevents FitTrack from counting time while the browser may stop delivering GPS updates. Tap Resume and keep FitTrack open.</p></section>`:''}<div class="grid grid-2" style="margin-top:14px"><button class="secondary-btn" data-activity-pause>${activity.status==='paused'?'Resume':'Pause'}</button><button class="primary-btn" data-activity-finish>Finish</button></div>`}
 function acceptFirst(p){activity.anchor=p;activity.points.push(p);activity.gpsReady=true;activity.lastMovementAt=Date.now();activity.lastGpsAt=Date.now();const ns=p.nativeSpeedKmh;if(Number.isFinite(ns)&&ns>=0&&ns<=limits(activity.type).maxSpeed)activity.currentSpeedKmh=ns}
 function onPosition(pos){
  if(!activity||activity.status!=='active')return;
  const c=pos.coords,lim=limits(activity.type),acc=Number(c.accuracy),lat=Number(c.latitude),lon=Number(c.longitude),ts=Number(pos.timestamp)||Date.now();
  if(!Number.isFinite(lat)||!Number.isFinite(lon))return;
  if(activity.lastRawTs&&ts<=activity.lastRawTs)return;activity.lastRawTs=ts;activity.lastGpsAt=Date.now();activity.lastAccuracy=Number.isFinite(acc)?acc:null;
  if(Number.isFinite(acc)&&acc>lim.accuracy){renderLive();return}
  const nativeSpeedKmh=Number.isFinite(Number(c.speed))&&Number(c.speed)>=0?Number(c.speed)*3.6:null,p={lat,lon,ts,accuracy:Number.isFinite(acc)?acc:null,nativeSpeedKmh};
  if(!activity.anchor){acceptFirst(p);renderLive();return}
  const prev=activity.anchor,d=hav(prev,p),meters=d*1000,dt=Math.max(.5,(p.ts-prev.ts)/1000),segmentSpeed=d/(dt/3600),avgAcc=((Number(prev.accuracy)||lim.accuracy)+(Number(p.accuracy)||lim.accuracy))/2,minMove=Math.max(lim.minMove,Math.min(lim.maxMove,avgAcc*.10));
  if(meters<minMove){if(Date.now()-(activity.lastMovementAt||0)>7000)activity.currentSpeedKmh=Math.max(0,Number(activity.currentSpeedKmh||0)*.55);renderLive();return}
  if(segmentSpeed>lim.maxSpeed){renderLive();return}
  let segmentDistance=d;
  if(dt>7&&nativeSpeedKmh!=null&&nativeSpeedKmh>0.8&&nativeSpeedKmh<=lim.maxSpeed){const speedDistance=nativeSpeedKmh*(dt/3600);segmentDistance=Math.max(d,Math.min(speedDistance,d*1.45+.003))}
  activity.distanceKm+=segmentDistance;activity.anchor=p;activity.points.push(p);activity.lastMovementAt=Date.now();
  let measured=segmentDistance/(dt/3600);if(nativeSpeedKmh!=null&&nativeSpeedKmh<=lim.maxSpeed)measured=measured*.45+nativeSpeedKmh*.55;const previousSpeed=Number(activity.currentSpeedKmh);activity.currentSpeedKmh=Number.isFinite(previousSpeed)?previousSpeed*.55+measured*.45:measured;renderLive()
 }
 function onError(err){console.warn('FitTrack GPS:',err?.message);toast?.('GPS unavailable. Check Precise Location permission.')}
 function pulseGps(){if(!activity||activity.status!=='active'||document.visibilityState!=='visible'||pulseBusy)return;pulseBusy=true;navigator.geolocation.getCurrentPosition(p=>{pulseBusy=false;onPosition(p)},e=>{pulseBusy=false;if(e?.code!==3)onError(e)},{enableHighAccuracy:true,maximumAge:0,timeout:4500})}
 function startGps(){stopGps();watchId=navigator.geolocation.watchPosition(onPosition,onError,{enableHighAccuracy:true,maximumAge:0,timeout:20000});gpsPulseTimer=setInterval(pulseGps,5000);pulseGps()}
 async function begin(type){if(!navigator.geolocation)return toast?.('GPS is not supported on this device');const u=await user();if(!u)return toast?.('Sign in to track an activity');let weightKg=70,heightCm=170;const{data:p}=await supabase.from('profiles').select('weight_kg,height_cm').eq('id',u.id).maybeSingle();if(p?.weight_kg)weightKg=Number(p.weight_kg);if(p?.height_cm)heightCm=Number(p.height_cm);activity={type,userId:u.id,status:'active',startedAt:new Date().toISOString(),segmentStartedAt:Date.now(),elapsedMs:0,distanceKm:0,points:[],anchor:null,gpsReady:false,lastAccuracy:null,lastGpsAt:null,lastRawTs:null,weightKg,heightCm,currentSpeedKmh:0,lastMovementAt:null,pausedByVisibility:false};startGps();tickTimer=setInterval(()=>activity?.status==='active'&&renderLive(),1000);requestWakeLock();renderLive()}
 window.fitTrackStartActivity=type=>{state.route='ride';document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route==='ride'));window.fitTrackRender?.();setTimeout(()=>begin(type),0)};
 function pause(fromVisibility=false){if(!activity)return;if(activity.status==='active'){activity.elapsedMs+=Date.now()-activity.segmentStartedAt;activity.status='paused';activity.currentSpeedKmh=0;activity.pausedByVisibility=!!fromVisibility;stopGps();releaseWakeLock()}else{activity.status='active';activity.segmentStartedAt=Date.now();activity.anchor=null;activity.lastRawTs=null;activity.currentSpeedKmh=0;activity.pausedByVisibility=false;startGps();requestWakeLock()}renderLive()}
 function stopGps(){if(watchId!==null)navigator.geolocation.clearWatch(watchId);watchId=null;if(gpsPulseTimer)clearInterval(gpsPulseTimer);gpsPulseTimer=null;pulseBusy=false}
 async function finish(){if(!activity)return;if(activity.status==='active')activity.elapsedMs+=Date.now()-activity.segmentStartedAt;activity.status='finished';stopGps();if(tickTimer)clearInterval(tickTimer);tickTimer=null;await releaseWakeLock();const m=metrics(),route={type:'LineString',coordinates:activity.points.map(p=>[p.lon,p.lat]),properties:{accuracy_m:activity.points.map(p=>p.accuracy??null),filter_version:'v4',accepted_samples:activity.points.length}};const{error}=await supabase.from('activity_sessions').insert({user_id:activity.userId,activity_type:activity.type,started_at:activity.startedAt,ended_at:new Date().toISOString(),duration_seconds:m.seconds,distance_km:Number(m.distance.toFixed(3)),avg_speed_kmh:Number(m.speed.toFixed(2)),avg_pace_min_per_km:m.distance?Number(m.pace.toFixed(2)):null,estimated_calories:m.calories,estimated_steps:activity.type==='cycle'?null:m.steps,route_geojson:route});if(error){toast?.('Could not save activity');activity.status='paused';return renderLive()}const type=activity.type;app.innerHTML=`<div class="page-head"><div class="eyebrow">Activity saved</div><h1 class="page-title">${type[0].toUpperCase()+type.slice(1)} complete</h1></div><section class="grid grid-2"><article class="card"><div class="metric">${m.distance.toFixed(2)}</div><div class="metric-label">km</div></article><article class="card"><div class="metric">${fmtTime(m.seconds)}</div><div class="metric-label">duration</div></article><article class="card"><div class="metric">${type==='cycle'?m.speed.toFixed(1):paceText(m.pace)}</div><div class="metric-label">${type==='cycle'?'avg km/h':'avg min/km'}</div></article><article class="card"><div class="metric">${m.calories}</div><div class="metric-label">estimated kcal</div></article></section><button class="primary-btn full-btn" data-activity-done>Done</button>`;activity=null}
 function maybe(){if(state.route!=='ride')return;activity?renderLive():chooser()}
 document.addEventListener('visibilitychange',()=>{if(!activity)return;if(document.visibilityState==='hidden'&&activity.status==='active')pause(true);else if(document.visibilityState==='visible'&&activity.status==='active')requestWakeLock();else if(document.visibilityState==='visible'&&activity.status==='paused')renderLive()});
 document.addEventListener('click',e=>{const s=e.target.closest('[data-activity-start]');if(s)return begin(s.dataset.activityStart);if(e.target.closest('[data-activity-pause]'))return pause(false);if(e.target.closest('[data-activity-finish]'))return finish();if(e.target.closest('[data-activity-done]'))return chooser();if(e.target.closest('[data-route="ride"]'))setTimeout(maybe,0)});
 new MutationObserver(()=>{if(observerBusy)return;observerBusy=true;setTimeout(()=>{observerBusy=false;if(state.route==='ride'&&!app.querySelector('[data-activity-start]')&&!app.querySelector('[data-activity-pause]')&&!app.querySelector('[data-activity-done]'))maybe()},40)}).observe(app,{childList:true});
})();