const state = {
  route: 'home',
  activeTab: 'Session',
  workout: { name: 'Chest A', exercises: [
    { name: 'Barbell Bench Press', target: 'Chest · Triceps · Front Delts', sets: [{weight:70,reps:10,done:true},{weight:70,reps:9,done:true},{weight:72.5,reps:8,done:false},{weight:72.5,reps:8,done:false}] },
    { name: 'Incline Dumbbell Press', target: 'Upper Chest · Triceps', sets: [{weight:24,reps:10,done:false},{weight:24,reps:10,done:false},{weight:24,reps:8,done:false}] },
    { name: 'Cable Crossover', target: 'Chest', sets: [{weight:17.5,reps:12,done:false},{weight:17.5,reps:12,done:false},{weight:17.5,reps:12,done:false}] }
  ]},
  rides:[],
  workoutHistory:[]
};
const app=document.getElementById('app'),toast=document.getElementById('toast');
function showToast(m){toast.textContent=m;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),1900)}
function navigate(route){state.route=route;if(route==='workout'&&!['Session','Planner','Library'].includes(state.activeTab))state.activeTab='Session';document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===route));render();window.scrollTo(0,0)}
function pageHead(e,t,c){return `<div class="page-head"><div class="eyebrow">${e}</div><h1 class="page-title">${t}</h1><p class="page-copy">${c}</p></div>`}
function localDate(){return new Date().toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'short'})}
function greeting(){const h=new Date().getHours();return h<12?'Good morning':h<17?'Good afternoon':'Good evening'}
function renderHome(){return `<div class="page-head"><h1 class="page-title">${greeting()}, Anirudh</h1><p class="page-copy">Your next session is ready. Keep the focus on consistency and clean progression.</p></div><div class="home-datetime"><div><div class="eyebrow">Today</div><div class="home-date">${new Date().toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</div></div><div class="home-time">${new Date().toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})}</div></div><section class="card hero-card"><div><div class="eyebrow">Today · Planner</div><h2 class="page-title home-hero-title">Loading today's workout…</h2><p class="page-copy">Your scheduled session will appear here.</p></div></section><section class="card home-activity-card"><div class="home-section-head"><div><div class="section-title">Activity</div><div class="card-title home-section-title">Start an activity</div></div><span class="home-section-hint">GPS starts after tap</span></div><div class="home-quick-actions"><button class="home-quick-action" data-home-start-activity="walk"><span class="home-quick-icon">W</span><span>Walk</span></button><button class="home-quick-action" data-home-start-activity="run"><span class="home-quick-icon">R</span><span>Run</span></button><button class="home-quick-action" data-home-start-activity="cycle"><span class="home-quick-icon">C</span><span>Cycle</span></button></div></section>`}
function renderWorkout(){const c=state.workout.exercises.reduce((s,e)=>s+e.sets.filter(x=>x.done).length,0),t=state.workout.exercises.reduce((s,e)=>s+e.sets.length,0);const tabs=['Session','Planner','Library'];let body='';if(state.activeTab==='Planner'){body=`<section class="card"><div class="section-title">Monthly plan</div><div class="card-title">Planner</div><p class="page-copy" style="margin-top:8px">Your saved workouts and scheduled sessions appear here.</p></section>`;}else if(state.activeTab==='Library'){body=`<section class="card"><div class="card-subtitle">Loading exercise library…</div></section>`;}else{state.activeTab='Session';body=`<section class="card" style="margin-bottom:14px"><div class="meta-row"><div><div class="section-title">Current session</div><div class="card-title">${c} / ${t} sets completed</div></div></div></section><div class="workout-shell">${state.workout.exercises.map((e,ei)=>`<section class="exercise-session"><div class="exercise-session-head"><div class="card-title">${e.name}</div><div class="card-subtitle">${e.target}</div></div><div class="exercise-session-body">${e.sets.map((s,si)=>`<div class="set-row"><div class="set-index">${si+1}</div><div class="set-value">${s.weight} kg</div><div class="set-value">${s.reps} reps</div><button class="set-complete ${s.done?'done':''}" data-action="toggle-set" data-ex="${ei}" data-set="${si}">${s.done?'✓ Done':'Complete'}</button></div>`).join('')}</div></section>`).join('')}</div>`;}return `${pageHead(`Workout · ${localDate()}`,'Workout','Session, planner and exercise library.')}<div class="tabs">${tabs.map(t=>`<button class="tab ${state.activeTab===t?'active':''}" data-tab="${t}">${t}</button>`).join('')}</div>${body}`}
function renderRide(){return `${pageHead('Activity','Outdoor tracking','Track walks, runs and cycling sessions.')}<section class="card"><div class="card-title">Choose an activity from Home or the Activity tracker.</div></section>`}
function renderHistory(){return `${pageHead('Activity log','History','Your completed workouts and activities.')}<section class="card"><div class="page-copy">Loading your history…</div></section>`}
function renderProgress(){return `${pageHead('Analytics','Progress','Track strength and activity progress over time.')}<section class="card"><div class="page-copy">Loading your progress…</div></section>`}
function render(){if(state.route==='home')app.innerHTML=renderHome();else if(state.route==='workout')app.innerHTML=renderWorkout();else if(state.route==='ride')app.innerHTML=renderRide();else if(state.route==='history')app.innerHTML=renderHistory();else app.innerHTML=renderProgress();wireEvents()}
function wireEvents(){document.querySelectorAll('[data-route]').forEach(x=>x.onclick=()=>navigate(x.dataset.route));document.querySelectorAll('[data-tab]').forEach(x=>x.onclick=()=>{state.activeTab=x.dataset.tab;render()});document.querySelectorAll('[data-action="start-workout"]').forEach(x=>x.onclick=()=>navigate('workout'));document.querySelectorAll('[data-action="toggle-set"]').forEach(x=>x.onclick=()=>{let s=state.workout.exercises[+x.dataset.ex].sets[+x.dataset.set];s.done=!s.done;render()});document.querySelectorAll('[data-home-start-activity]').forEach(x=>x.onclick=()=>window.fitTrackStartActivity?.(x.dataset.homeStartActivity));}
window.fitTrackState=state;
window.fitTrackRender=render;
window.fitTrackShowToast=showToast;
render();
