const state = {
  route: 'home',
  activeTab: 'All',
  workout: { name: 'Chest A', exercises: [
    { name: 'Barbell Bench Press', target: 'Chest · Triceps · Front Delts', sets: [{weight:70,reps:10,done:true},{weight:70,reps:9,done:true},{weight:72.5,reps:8,done:false},{weight:72.5,reps:8,done:false}] },
    { name: 'Incline Dumbbell Press', target: 'Upper Chest · Triceps', sets: [{weight:24,reps:10,done:false},{weight:24,reps:10,done:false},{weight:24,reps:8,done:false}] },
    { name: 'Cable Crossover', target: 'Chest', sets: [{weight:17.5,reps:12,done:false},{weight:17.5,reps:12,done:false},{weight:17.5,reps:12,done:false}] }
  ]},
  rides:[{date:'18 Aug',name:'Morning Ride',distance:18.7,duration:'47:52',calories:486},{date:'16 Aug',name:'Weekend Ride',distance:24.4,duration:'1:01:18',calories:612},{date:'13 Aug',name:'Evening Ride',distance:12.6,duration:'33:47',calories:318}],
  workoutHistory:[{date:'18 Aug',name:'Chest A',duration:'52 min',volume:'7,420 kg'},{date:'17 Aug',name:'Back A',duration:'56 min',volume:'8,110 kg'},{date:'15 Aug',name:'Legs A',duration:'61 min',volume:'11,280 kg'}]
};
const app=document.getElementById('app'),toast=document.getElementById('toast');
function showToast(m){toast.textContent=m;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),1900)}
function navigate(route){state.route=route;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===route));render();window.scrollTo(0,0)}
function pageHead(e,t,c){return `<div class="page-head"><div class="eyebrow">${e}</div><h1 class="page-title">${t}</h1><p class="page-copy">${c}</p></div>`}
function renderHome(){return `${pageHead('Tuesday · 18 Aug','Good evening, Anirudh','Your next session is ready. Keep the focus on consistency and clean progression.')}<section class="card hero-card"><div><div class="eyebrow">Today · Strength</div><h2 class="page-title" style="font-size:34px;margin-top:8px">${state.workout.name}</h2><p class="page-copy">4 exercises · 15 planned sets · ~52 min</p></div><button class="primary-btn" data-action="start-workout">Start workout →</button></section><div style="height:14px"></div><div class="section-title">Activity</div><section class="grid grid-4"><article class="card activity-card"><div class="activity-icon">⌁</div><div><div class="metric metric-sm">52 min</div><div class="metric-label">Gym</div></div></article><article class="card activity-card"><div class="activity-icon">◉</div><div><div class="metric metric-sm">18.7 km</div><div class="metric-label">Ride</div></div></article><article class="card activity-card"><div class="activity-icon">✓</div><div><div class="metric metric-sm">2 / 10</div><div class="metric-label">Sets today</div></div></article><article class="card activity-card"><div class="activity-icon">4</div><div><div class="metric metric-sm">4 days</div><div class="metric-label">Streak</div></div></article></section>`}
function renderWorkout(){const c=state.workout.exercises.reduce((s,e)=>s+e.sets.filter(x=>x.done).length,0),t=state.workout.exercises.reduce((s,e)=>s+e.sets.length,0);let tabs=['Session','Planner','Library'];let body='';if(state.activeTab==='Session')body=`<section class="card" style="margin-bottom:14px"><div class="meta-row"><div><div class="section-title">Planned session</div><div class="card-title">${c} / ${t} sets completed</div></div></div></section><div class="workout-shell">${state.workout.exercises.map((e,ei)=>`<section class="exercise-session"><div class="exercise-session-head"><div class="card-title">${e.name}</div><div class="card-subtitle">${e.target}</div></div><div class="exercise-session-body">${e.sets.map((s,si)=>`<div class="set-row"><div class="set-index">${si+1}</div><div class="set-value">${s.weight} kg</div><div class="set-value">${s.reps} reps</div><button class="set-complete ${s.done?'done':''}" data-action="toggle-set" data-ex="${ei}" data-set="${si}">${s.done?'✓ Done':'Complete'}</button></div>`).join('')}</div></section>`).join('')}</div>`;else if(state.activeTab==='Planner')body=`<section class="card"><div class="section-title">Monthly plan</div><div class="card-title">September 2026</div><p class="page-copy" style="margin-top:8px">Your planned training days will appear here.</p><div class="calendar">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=>`<div class="calendar-head">${d}</div>`).join('')}${Array.from({length:28},(_,i)=>`<div class="calendar-day"><div class="date">${i+1}</div><div class="plan">${['CHEST','BACK','REST','LEGS','ARMS','RIDE','REST'][i%7]}</div></div>`).join('')}</div></section>`;else body=`<section class="grid grid-2">${['Chest','Back','Shoulders','Quads','Hamstrings','Glutes','Biceps','Triceps'].map(x=>`<article class="card"><div class="card-title">${x}</div><div class="card-subtitle">Exercise library</div></article>`).join('')}</section>`;return `${pageHead('Workout planner · Tuesday 18 Aug',state.workout.name,'Your training session, planner and exercise library.') }<div class="tabs">${tabs.map(t=>`<button class="tab ${state.activeTab===t?'active':''}" data-tab="${t}">${t}</button>`).join('')}</div>${body}`}
function renderRide(){return `${pageHead('Cycling','Ride tracking','Track cycling sessions and review your saved rides.')}<section class="card"><div class="map-panel"><div class="map-grid"></div><div class="map-label">GPS preview</div></div><div class="ride-stats"><div class="card"><div class="metric">18.72</div><div class="metric-label">km</div></div><div class="card"><div class="metric">23.4</div><div class="metric-label">avg km/h</div></div><div class="card"><div class="metric">47:52</div><div class="metric-label">duration</div></div><div class="card"><div class="metric">486</div><div class="metric-label">kcal</div></div></div></section>`}
function renderHistory(){return `${pageHead('Activity log','History','Your completed workouts and rides.')}<section class="card"><div class="list">${state.workoutHistory.map(x=>`<div class="list-row"><div><div class="list-row-title">${x.name}</div><div class="list-row-meta">${x.date} · ${x.duration}</div></div><strong>${x.volume}</strong></div>`).join('')}</div></section>`}
function renderProgress(){return `${pageHead('Analytics','Progress','Track strength and cycling progress over time.')}<section class="grid grid-2"><article class="card"><div class="card-title">Bench Press</div><div class="metric" style="margin-top:20px">75 kg</div><div class="metric-label">current top set</div></article><article class="card"><div class="card-title">August distance</div><div class="metric" style="margin-top:20px">126.4 km</div><div class="metric-label">cycling</div></article></section>`}
function render(){if(state.route==='home')app.innerHTML=renderHome();else if(state.route==='workout')app.innerHTML=renderWorkout();else if(state.route==='ride')app.innerHTML=renderRide();else if(state.route==='history')app.innerHTML=renderHistory();else app.innerHTML=renderProgress();wireEvents()}
function wireEvents(){document.querySelectorAll('[data-route]').forEach(x=>x.onclick=()=>navigate(x.dataset.route));document.querySelectorAll('[data-tab]').forEach(x=>x.onclick=()=>{state.activeTab=x.dataset.tab;render()});document.querySelectorAll('[data-action="start-workout"]').forEach(x=>x.onclick=()=>navigate('workout'));document.querySelectorAll('[data-action="toggle-set"]').forEach(x=>x.onclick=()=>{let s=state.workout.exercises[+x.dataset.ex].sets[+x.dataset.set];s.done=!s.done;render()});}
render();
