// FitTrack workout + activity History with drill-down.
(function(){
 const supabase=window.fitTrackSupabase,state=window.fitTrackState,toast=window.fitTrackShowToast;if(!supabase||!state)return;
 let viewMode='list',historyTab='Workouts',requestToken=0;
 const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
 const title=v=>{const s=String(v||'activity');return s.charAt(0).toUpperCase()+s.slice(1)};
 const date=(v,long=false)=>new Date(v).toLocaleDateString(undefined,long?{day:'numeric',month:'long',year:'numeric'}:{day:'numeric',month:'short'});
 const duration=s=>{s=Number(s||0);return s<60?`${Math.round(s)} sec`:s<3600?`${Math.round(s/60)} min`:`${Math.floor(s/3600)}h ${Math.round((s%3600)/60)}m`};
 async function user(){const{data,error}=await supabase.auth.getUser();return error?null:(data.user||null)}
 function tabs(){return `<div class="tabs" style="margin-bottom:14px">${['Workouts','Activities'].map(t=>`<button class="tab ${historyTab===t?'active':''}" data-history-tab="${t}">${t}</button>`).join('')}</div>`}
 async function render(){if(state.route!=='history'||viewMode!=='list')return;const token=++requestToken,u=await user();if(!u||token!==requestToken)return;const app=document.getElementById('app');if(historyTab==='Workouts'){const{data,error}=await supabase.from('completed_workouts').select('id,workout_name,total_volume_kg,completed_sets,duration_seconds,completed_at').eq('user_id',u.id).order('completed_at',{ascending:false}).limit(50);if(error||token!==requestToken)return;app.innerHTML=`<div class="page-head"><div class="eyebrow">Activity log</div><h1 class="page-title">History</h1><p class="page-copy">Your completed workouts and outdoor activities.</p></div>${tabs()}<section class="card"><div class="list">${!data?.length?`<div class="list-row"><div class="list-row-title">No completed workouts yet</div></div>`:data.map(r=>`<button class="list-row" data-workout-detail="${r.id}" style="width:100%;text-align:left;color:inherit"><div><div class="list-row-title">${esc(r.workout_name)}</div><div class="list-row-meta">${date(r.completed_at)} · ${duration(r.duration_seconds)} · ${r.completed_sets} sets</div></div><div><strong>${Number(r.total_volume_kg||0).toLocaleString()} kg</strong> <span class="accent">→</span></div></button>`).join('')}</div></section>`;return;}
 const{data,error}=await supabase.from('activity_sessions').select('id,activity_type,started_at,duration_seconds,distance_km,avg_speed_kmh,avg_pace_min_per_km,estimated_calories').eq('user_id',u.id).order('started_at',{ascending:false}).limit(50);if(error||token!==requestToken)return;app.innerHTML=`<div class="page-head"><div class="eyebrow">Activity log</div><h1 class="page-title">History</h1><p class="page-copy">Your completed workouts and outdoor activities.</p></div>${tabs()}<section class="card"><div class="list">${!data?.length?`<div class="list-row"><div class="list-row-title">No activities yet</div></div>`:data.map(r=>{const metric=r.activity_type==='cycle'?`${Number(r.avg_speed_kmh||0).toFixed(1)} km/h`:(r.avg_pace_min_per_km?`${Number(r.avg_pace_min_per_km).toFixed(1)} min/km`:'—');return `<button class="list-row" data-activity-detail="${r.id}" style="width:100%;text-align:left;color:inherit"><div><div class="list-row-title">${title(r.activity_type)}</div><div class="list-row-meta">${date(r.started_at)} · ${duration(r.duration_seconds)} · ${Number(r.distance_km||0).toFixed(2)} km · ${metric}</div></div><div><strong>${Number(r.estimated_calories||0)} kcal</strong> <span class="accent">→</span></div></button>`}).join('')}</div></section>`;}
 async function workoutDetail(id){viewMode='detail';const token=++requestToken,u=await user();if(!u)return;const{data,error}=await supabase.from('completed_workouts').select('workout_name,workout_state,total_volume_kg,completed_sets,duration_seconds,completed_at').eq('user_id',u.id).eq('id',id).single();if(error||token!==requestToken){viewMode='list';toast?.('Could not open workout');return render()}const ex=(data.workout_state?.exercises||[]).filter(x=>x.sets?.some(s=>s.done));document.getElementById('app').innerHTML=`<div class="page-head"><div class="eyebrow">Completed workout · ${date(data.completed_at,true)}</div><h1 class="page-title">${esc(data.workout_name)}</h1><p class="page-copy">${duration(data.duration_seconds)} · ${data.completed_sets} sets · ${Number(data.total_volume_kg||0).toLocaleString()} kg volume</p></div><button class="ghost-btn" data-back-history>← Back to History</button><div class="workout-shell" style="margin-top:14px">${ex.map(x=>`<section class="exercise-session"><div class="exercise-session-head"><div class="card-title">${esc(x.name)}</div></div><div class="exercise-session-body">${x.sets.map((s,i)=>`<div class="set-row" style="opacity:${s.done?1:.45}"><div class="set-index">${i+1}</div><div class="set-value">${Number(s.weight||0)} kg</div><div class="set-value">${Number(s.reps||0)} reps</div><div class="set-complete ${s.done?'done':''}">${s.done?'✓ Done':'Not completed'}</div></div>`).join('')}</div></section>`).join('')}</div>`;}
 async function activityDetail(id){viewMode='activity-detail';const token=++requestToken,u=await user();if(!u)return;const{data:r,error}=await supabase.from('activity_sessions').select('activity_type,started_at,ended_at,duration_seconds,distance_km,avg_speed_kmh,avg_pace_min_per_km,estimated_calories,route_geojson').eq('user_id',u.id).eq('id',id).single();if(error||token!==requestToken){viewMode='list';toast?.('Could not open activity');return render()}const pace=r.activity_type==='cycle'?`${Number(r.avg_speed_kmh||0).toFixed(1)} km/h`:(r.avg_pace_min_per_km?`${Number(r.avg_pace_min_per_km).toFixed(1)} min/km`:'—');const points=Array.isArray(r.route_geojson?.coordinates)?r.route_geojson.coordinates.length:0;document.getElementById('app').innerHTML=`<div class="page-head"><div class="eyebrow">Completed activity · ${date(r.started_at,true)}</div><h1 class="page-title">${title(r.activity_type)}</h1><p class="page-copy">Saved outdoor activity</p></div><button class="ghost-btn" data-back-history>← Back to History</button><section class="grid grid-4" style="margin-top:14px"><article class="card activity-card"><div class="eyebrow">Distance</div><div class="metric metric-sm">${Number(r.distance_km||0).toFixed(2)}</div><div class="metric-label">km</div></article><article class="card activity-card"><div class="eyebrow">Duration</div><div class="metric metric-sm">${duration(r.duration_seconds)}</div><div class="metric-label">active time</div></article><article class="card activity-card"><div class="eyebrow">${r.activity_type==='cycle'?'Avg speed':'Avg pace'}</div><div class="metric metric-sm">${pace}</div><div class="metric-label">average</div></article><article class="card activity-card"><div class="eyebrow">Calories</div><div class="metric metric-sm">${Number(r.estimated_calories||0)}</div><div class="metric-label">estimated kcal</div></article></section><section class="card" style="margin-top:14px"><div class="section-title">GPS route</div><div class="card-title">${points?`${points} GPS points saved`:'No route points recorded'}</div><p class="page-copy" style="margin-top:8px">The route data is stored. A visual route map can be added during the UI/map polish stage.</p></section>`;}
 document.addEventListener('click',e=>{const t=e.target.closest('[data-history-tab]');if(t){e.preventDefault();historyTab=t.dataset.historyTab;viewMode='list';render();return}const w=e.target.closest('[data-workout-detail]');if(w){e.preventDefault();workoutDetail(w.dataset.workoutDetail);return}const a=e.target.closest('[data-activity-detail]');if(a){e.preventDefault();activityDetail(a.dataset.activityDetail);return}if(e.target.closest('[data-back-history]')){e.preventDefault();viewMode='list';render();return}const n=e.target.closest('[data-route]');if(n){++requestToken;viewMode='list';if(n.dataset.route==='history')setTimeout(render,0)}},true);
 new MutationObserver(()=>{if(state.route==='history'&&viewMode==='list'&&!document.querySelector('[data-history-tab]'))render()}).observe(document.getElementById('app'),{childList:true});
})();
