// FitTrack Home: real scheduled workout, live local date/time, quick activities.
(function(){
 const supabase=window.fitTrackSupabase,app=document.getElementById('app'),state=window.fitTrackState;if(!supabase||!app||!state)return;
 let token=0,busy=false,clockTimer=null;
 async function getUser(){const {data,error}=await supabase.auth.getUser();return error?null:(data.user||null)}
 function todayISO(){const d=new Date(),local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,10)}
 function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
 function isHome(){return state.route==='home'&&!!app.querySelector('.hero-card')}
 function greeting(){const h=new Date().getHours();return h<12?'Good morning':h<17?'Good afternoon':'Good evening'}
 function updateHeader(){if(!isHome())return;const head=app.querySelector('.page-head');if(head){const now=new Date();const shortDate=now.toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'short'});head.innerHTML=`<div class="eyebrow">${shortDate}</div><h1 class="page-title">${greeting()}, Anirudh</h1><p class="page-copy">Your next session is ready. Keep the focus on consistency and clean progression.</p>`}}
 function updateClock(){const box=app.querySelector('[data-home-datetime]');if(!box)return;const now=new Date(),date=now.toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long',year:'numeric'}),time=now.toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'});box.innerHTML=`<div><div class="eyebrow">Today</div><div class="home-date">${date}</div></div><div class="home-time">${time}</div>`;updateHeader()}
 function injectDateTime(){if(!isHome())return;updateHeader();let box=app.querySelector('[data-home-datetime]');if(!box){box=document.createElement('div');box.className='home-datetime';box.dataset.homeDatetime='1';app.querySelector('.hero-card')?.insertAdjacentElement('beforebegin',box)}updateClock();if(!clockTimer)clockTimer=setInterval(()=>{if(isHome())updateClock();else{clearInterval(clockTimer);clockTimer=null}},1000)}
 function reveal(){app.style.visibility='visible';app.style.opacity='1'}
 function injectQuickActivities(){if(!isHome()||app.querySelector('[data-home-quick-activities]'))return;const hero=app.querySelector('.hero-card');if(!hero)return;const section=document.createElement('section');section.className='card home-activity-card';section.dataset.homeQuickActivities='1';section.innerHTML=`<div class="home-section-head"><div><div class="section-title">Outdoor activity</div><div class="card-title home-section-title">Start something else</div></div><span class="home-section-hint">GPS starts after tap</span></div><div class="home-quick-actions"><button class="home-quick-action" data-home-start-activity="walk"><span class="home-quick-icon">W</span><span>Walk</span></button><button class="home-quick-action" data-home-start-activity="run"><span class="home-quick-icon">R</span><span>Run</span></button><button class="home-quick-action" data-home-start-activity="cycle"><span class="home-quick-icon">C</span><span>Cycle</span></button></div>`;hero.insertAdjacentElement('afterend',section)}
 async function enhanceHome(){if(!isHome()){reveal();return}injectDateTime();const myToken=++token,user=await getUser();if(!user||myToken!==token||!isHome()){reveal();return}const {data:planned,error}=await supabase.from('planned_sessions').select('id,template_id,session_date,name,status').eq('user_id',user.id).eq('session_date',todayISO()).eq('status','planned').order('id',{ascending:true}).limit(1).maybeSingle();if(error||myToken!==token||!isHome()){reveal();return}const hero=app.querySelector('.hero-card');if(!hero){reveal();return}if(!planned){hero.innerHTML=`<div><div class="eyebrow">Today · Planner</div><h2 class="page-title home-hero-title">No workout scheduled</h2><p class="page-copy">Plan a workout for today, or start an outdoor activity below.</p></div><button class="primary-btn home-primary-action" data-fit-home-planner>Open Planner →</button>`;injectQuickActivities();reveal();return}const {data:rows}=await supabase.from('workout_template_exercises').select('planned_sets').eq('template_id',planned.template_id);if(myToken!==token||!isHome()){reveal();return}const exercises=(rows||[]).length,sets=(rows||[]).reduce((sum,row)=>sum+Math.max(1,Number(row.planned_sets||0)),0);hero.innerHTML=`<div><div class="eyebrow">Today · Strength</div><h2 class="page-title home-hero-title">${esc(planned.name)}</h2><p class="page-copy">${exercises} exercise${exercises===1?'':'s'} · ${sets} planned set${sets===1?'':'s'}</p></div><button class="primary-btn home-primary-action" data-fit-session-load="${planned.id}">Start workout →</button>`;injectQuickActivities();reveal()}
 document.addEventListener('click',event=>{const planner=event.target.closest('[data-fit-home-planner]');if(planner){event.preventDefault();state.route='workout';state.activeTab='Planner';document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route==='workout'));window.fitTrackRender?.();window.scrollTo(0,0);return}const btn=event.target.closest('[data-home-start-activity]');if(btn){event.preventDefault();window.fitTrackStartActivity?.(btn.dataset.homeStartActivity)}});
 const observer=new MutationObserver(()=>{if(busy)return;busy=true;setTimeout(()=>{busy=false;enhanceHome()},25)});observer.observe(app,{childList:true,subtree:true});setTimeout(enhanceHome,40);setTimeout(reveal,1500);
})();