// FitTrack Progress V2: exercise progression, PRs, bodyweight log and lightweight charts.
(function(){
 const supabase=window.fitTrackSupabase,state=window.fitTrackState,app=document.getElementById('app'),toast=window.fitTrackShowToast;if(!supabase||!state||!app)return;
 let loading=false;const BW_KEY='fittrackBodyweightLog';
 const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
 async function user(){const{data}=await supabase.auth.getUser();return data?.user||null}
 function bwLog(){try{return JSON.parse(localStorage.getItem(BW_KEY)||'[]')}catch{return[]}}
 function saveBw(v){const arr=bwLog();arr.push({date:new Date().toISOString(),kg:Number(v)});localStorage.setItem(BW_KEY,JSON.stringify(arr.slice(-180)));return arr}
 function spark(points,label='kg'){if(!points.length)return '<div class="page-copy">No data yet.</div>';const vals=points.map(p=>Number(p.value||0)),min=Math.min(...vals),max=Math.max(...vals),span=Math.max(1,max-min),w=520,h=150,pad=14;const coords=points.map((p,i)=>{const x=pad+(i/(Math.max(1,points.length-1)))*(w-pad*2),y=h-pad-((Number(p.value)-min)/span)*(h-pad*2);return `${x.toFixed(1)},${y.toFixed(1)}`}).join(' ');return `<svg viewBox="0 0 ${w} ${h}" class="progress-v2-chart" role="img" aria-label="Progress chart"><polyline points="${coords}" fill="none" stroke="var(--accent)" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/><line x1="${pad}" y1="${h-pad}" x2="${w-pad}" y2="${h-pad}" stroke="rgba(255,255,255,.08)"/><text x="${pad}" y="16" fill="var(--muted)" font-size="11">${max.toFixed(1)} ${label}</text><text x="${pad}" y="${h-2}" fill="var(--muted)" font-size="11">${min.toFixed(1)} ${label}</text></svg>`}
 async function enhance(){
   if(state.route!=='progress'||loading||app.querySelector('[data-progress-v2]')||!app.querySelector('[data-real-progress]'))return;loading=true;
   const u=await user();if(!u){loading=false;return}
   const{data:rows}=await supabase.from('completed_workouts').select('workout_state,completed_at').eq('user_id',u.id).order('completed_at',{ascending:true}).limit(200);
   if(state.route!=='progress'){loading=false;return}
   const map=new Map();for(const r of rows||[]){for(const ex of r.workout_state?.exercises||[]){const done=(ex.sets||[]).filter(s=>s.done);if(!done.length)continue;const maxWeight=Math.max(...done.map(s=>Number(s.weight||0)));const max1rm=Math.max(...done.map(s=>Number(s.weight||0)*(1+Number(s.reps||0)/30)));const arr=map.get(ex.name)||[];arr.push({date:r.completed_at,maxWeight,max1rm});map.set(ex.name,arr)}}
   const names=[...map.keys()].sort();const first=names[0]||'';const holder=document.createElement('section');holder.className='card progress-v2';holder.dataset.progressV2='1';holder.innerHTML=`<div class="section-title">Exercise progression</div><div class="meta-row"><div><div class="card-title">Strength by exercise</div><div class="card-subtitle">Track top weight and estimated 1RM over time.</div></div>${names.length?`<select class="auth-input" data-progress-exercise-select>${names.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('')}</select>`:''}</div><div data-progress-exercise-detail style="margin-top:14px"></div><div class="progress-v2-divider"></div><div class="section-title">Bodyweight</div><div class="grid grid-2"><div><div class="card-title">Log bodyweight</div><div class="card-subtitle">Saved on this device and current weight synced to your profile.</div><div class="progress-v2-weight-form"><input class="auth-input" type="number" inputmode="decimal" step="0.1" min="30" max="300" placeholder="Weight in kg" data-bodyweight-input><button class="primary-btn" data-bodyweight-save>Save</button></div></div><div data-bodyweight-summary></div></div>`;
   app.querySelector('[data-real-progress]')?.appendChild(holder);
   function renderExercise(name){const pts=map.get(name)||[];const best=pts.length?Math.max(...pts.map(p=>p.maxWeight)):0,best1=pts.length?Math.max(...pts.map(p=>p.max1rm)):0;holder.querySelector('[data-progress-exercise-detail]').innerHTML=pts.length?`<div class="grid grid-3"><article class="progress-v2-stat"><strong>${best.toFixed(1)} kg</strong><span>Heaviest set</span></article><article class="progress-v2-stat"><strong>${best1.toFixed(1)} kg</strong><span>Est. 1RM PR</span></article><article class="progress-v2-stat"><strong>${pts.length}</strong><span>Sessions</span></article></div>${spark(pts.slice(-12).map(p=>({value:p.maxWeight})),'kg')}`:'<div class="page-copy">Complete this exercise in multiple workouts to see progression.</div>'}
   function renderBw(){const arr=bwLog(),latest=arr.at(-1)?.kg;holder.querySelector('[data-bodyweight-summary]').innerHTML=`<div class="progress-v2-stat"><strong>${latest?`${Number(latest).toFixed(1)} kg`:'—'}</strong><span>Latest</span></div>${spark(arr.slice(-20).map(x=>({value:x.kg})),'kg')}`}
   renderExercise(first);renderBw();holder.querySelector('[data-progress-exercise-select]')?.addEventListener('change',e=>renderExercise(e.target.value));holder.querySelector('[data-bodyweight-save]')?.addEventListener('click',async()=>{const input=holder.querySelector('[data-bodyweight-input]'),v=Number(input.value);if(!v||v<30||v>300)return toast?.('Enter a valid bodyweight');saveBw(v);await supabase.from('profiles').update({weight_kg:v}).eq('id',u.id);input.value='';renderBw();toast?.('Bodyweight saved')});loading=false;
 }
 new MutationObserver(()=>setTimeout(enhance,40)).observe(app,{childList:true,subtree:true});document.addEventListener('click',e=>{if(e.target.closest('[data-route="progress"]'))setTimeout(enhance,120)});setTimeout(enhance,180);
})();